/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as F1RouteImport } from './routes/f1'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as BookingCodeRouteImport } from './routes/booking.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const F1Route = F1RouteImport.update({
  id: '/f1',
  path: '/f1',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCodeRoute = BookingCodeRouteImport.update({
  id: '/booking/$code',
  path: '/booking/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/drivers': typeof DriversRoute
  '/f1': typeof F1Route
  '/teams': typeof TeamsRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/drivers': typeof DriversRoute
  '/f1': typeof F1Route
  '/teams': typeof TeamsRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/drivers': typeof DriversRoute
  '/f1': typeof F1Route
  '/teams': typeof TeamsRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/book' | '/drivers' | '/f1' | '/teams' | '/booking/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/book' | '/drivers' | '/f1' | '/teams' | '/booking/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/drivers'
    | '/f1'
    | '/teams'
    | '/booking/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  DriversRoute: typeof DriversRoute
  F1Route: typeof F1Route
  TeamsRoute: typeof TeamsRoute
  BookingCodeRoute: typeof BookingCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1': {
      id: '/f1'
      path: '/f1'
      fullPath: '/f1'
      preLoaderRoute: typeof F1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$code': {
      id: '/booking/$code'
      path: '/booking/$code'
      fullPath: '/booking/$code'
      preLoaderRoute: typeof BookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  DriversRoute: DriversRoute,
  F1Route: F1Route,
  TeamsRoute: TeamsRoute,
  BookingCodeRoute: BookingCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
